export const SET_CONTEST_END_TIME = "SET_CONTEST_END_TIME";
export const UPDATE_CONTEST_TIME = "UPDATE_CONTEST_TIME";
export const CONTEST_END = "CONTEST_END";
export const CONTEST_START = "CONTEST_START";
export const CONTEST_NOT_STARTED = "CONTEST_NOT_STARTED";
export const CONTEST_RESET = 'CONTEST_RESET'
