version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: yarn install --pure-lockfile
      - run:
          name: Check Prettier, ESLint, Flow
          command: yarn ci-check